import {headers,Issue,Specimen,UndoEntry} from './types';
export const required=['collectionNo','collector','date','location'] as const;
export const validDate=(s:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const[y,m,d]=s.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d};
// 仅接受十进制度数文本（可带符号与小数），拒绝十六进制、科学计数法等其他 Number 可解析格式
const decimalDegrees=/^[+-]?(\d+(\.\d+)?|\.\d+)$/;
export const validCoords=(lat:string,lon:string)=>{const la=lat.trim(),lo=lon.trim();return decimalDegrees.test(la)&&decimalDegrees.test(lo)&&Number(la)>=-90&&Number(la)<=90&&Number(lo)>=-180&&Number(lo)<=180};
const pad2=(n:number)=>String(n).padStart(2,'0');
// “当前日期”按本地时区取，避免本地零点后 UTC 仍停留在昨天而误报未来日期
export const localToday=(d=new Date())=>`${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`;
export function issuesFor(rows:Specimen[],today=localToday()):Issue[]{const counts=new Map<string,number>();rows.forEach(r=>{const no=r.collectionNo.trim();counts.set(no,(counts.get(no)||0)+1)});return rows.flatMap(r=>{const x:Issue[]=[];if(!r.species.trim())x.push({key:`${r.id}:species`,type:'物种名缺失',recordId:r.id});if(validDate(r.date)&&r.date>today)x.push({key:`${r.id}:future`,type:'日期晚于当前日期',recordId:r.id});if(!validCoords(r.latitude,r.longitude))x.push({key:`${r.id}:coords`,type:'经纬度不合法',recordId:r.id});const no=r.collectionNo.trim();if(no&&counts.get(no)!==1)x.push({key:`${r.id}:duplicate`,type:'采集编号重复',recordId:r.id});return x})}
export const speciesCount=(rows:Specimen[])=>new Set(rows.map(r=>r.species.trim()).filter(Boolean)).size;
// 纯语法解析：按引号规则切分并保留原始列值（含首尾空格），是否去空格由调用方决定
export function csvLine(line:string){const out:string[]=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&quote){cur+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
export type RawSpecimen=Omit<Specimen,'id'|'resolutions'>;
// 行级校验：必填、日期、坐标与重复编号规则，标准 CSV 与映射导入共用同一套；batch 累计本批已见编号
export function checkRow(n:number,r:RawSpecimen,seen:Set<string>,batch:Set<string>,push:(msg:string)=>void):Specimen{[['采集编号',r.collectionNo],['采集人',r.collector],['采集日期',r.date],['地点',r.location]].forEach(([k,x])=>{if(!x)push(`第 ${n} 行：${k}为必填项`)});if(r.date&&!validDate(r.date))push(`第 ${n} 行：采集日期不合法`);if(!validCoords(r.latitude,r.longitude))push(`第 ${n} 行：经纬度超出范围或缺失`);if(r.collectionNo&&(seen.has(r.collectionNo)||batch.has(r.collectionNo)))push(`第 ${n} 行：采集编号 ${r.collectionNo} 重复`);batch.add(r.collectionNo);return{id:crypto.randomUUID(),...r,resolutions:{}}}
export function importCsv(text:string,existing:Specimen[]):{rows?:Specimen[];errors:string[]}{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const errors:string[]=[];if(!lines.length)return{errors:['文件为空']};const got=csvLine(lines[0]).map(x=>x.trim());/* 标准路径沿用原规则：单元格去首尾空格 */if(got.length!==headers.length||got.some((h,i)=>h!==headers[i]))return{errors:[`第 1 行：表头必须为 ${headers.join(',')}`]};const seen=new Set(existing.map(x=>x.collectionNo));const batch=new Set<string>();const rows=lines.slice(1).map((line,i)=>{const n=i+2,v=csvLine(line).map(x=>x.trim());if(v.length!==8){errors.push(`第 ${n} 行：列数应为 8`);return null}const [collectionNo,species,collector,date,location,latitude,longitude,habitat]=v;return checkRow(n,{collectionNo,species,collector,date,location,latitude,longitude,habitat},seen,batch,m=>errors.push(m))}).filter(Boolean) as Specimen[];return errors.length?{errors}:{rows,errors:[]}}
export const samples:Specimen[]=[{id:'sample-1',collectionNo:'BJ-2026-001',species:'银杏 Ginkgo biloba',collector:'林青',date:'2026-05-18',location:'北京植物园',latitude:'39.99',longitude:'116.21',habitat:'园区林缘，向阳',resolutions:{}},{id:'sample-2',collectionNo:'YN-2026-014',species:'',collector:'周野',date:'2026-11-03',location:'云南高黎贡山',latitude:'91',longitude:'98.78',habitat:'常绿阔叶林下',resolutions:{}}];
export const UNDO_KEY='plant-preflight-undo-v1';
const isRecord=(x:unknown):x is Record<string,unknown>=>typeof x==='object'&&x!==null;
const strField=(x:Record<string,unknown>,k:string)=>typeof x[k]==='string';
export function isSpecimen(x:unknown):x is Specimen{if(!isRecord(x))return false;const f=['id','collectionNo','species','collector','date','location','latitude','longitude','habitat'];if(!f.every(k=>strField(x,k)))return false;if(!isRecord(x.resolutions)||Object.values(x.resolutions as Record<string,unknown>).some(v=>!isRecord(v)||(v.status!=='pending'&&v.status!=='fixed'&&v.status!=='kept')||typeof v.note!=='string'))return false;return true}
export function parseBackup(text:string):Specimen[]|null{let x:unknown;try{x=JSON.parse(text)}catch{return null}if(!Array.isArray(x)||!x.every(isSpecimen))return null;const seen=new Set<string>();return x.map(r=>r.id&&!seen.has(r.id)?(seen.add(r.id),r):{...r,id:crypto.randomUUID()})}
export function parseUndo(text:string|null):UndoEntry|null{try{if(!text)return null;const x:unknown=JSON.parse(text);if(!isRecord(x)||typeof x.id!=='string'||typeof x.savedAt!=='string'||!isSpecimen(x.snapshot)||x.snapshot.id!==x.id)return null;return{id:x.id,snapshot:x.snapshot,savedAt:x.savedAt}}catch{return null}}
export function loadUndo():UndoEntry|'invalid'|null{try{const text=localStorage.getItem(UNDO_KEY);if(text===null)return null;return parseUndo(text)??'invalid'}catch{return'invalid'}}
export function saveUndo(id:string,snapshot:Specimen,savedAt=new Date().toISOString()):UndoEntry{const e={id,snapshot,savedAt};try{localStorage.setItem(UNDO_KEY,JSON.stringify(e))}catch{}return e}
export function clearUndo(){try{localStorage.removeItem(UNDO_KEY)}catch{}}
export function consumeUndo(rows:Specimen[],entry:UndoEntry):Specimen[]|null{if(!rows.some(r=>r.id===entry.id))return null;return rows.map(r=>r.id===entry.id?structuredClone(entry.snapshot):r)}
